In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

ModuleNotFoundError: No module named 'scipy'

In [3]:
data = pd.read_stata('C:\\Users\\bayle\\Documents\\HW4.dta')
display(data)

person_ID  year  log_wage
0            4.0  1982  9.615806
1            5.0  1974  9.479604
2            5.0  1975  9.384294
3            5.0  1976  7.228388
4            5.0  1977  9.428673
...          ...   ...       ...
33774    35355.0  1975  9.026418
33775    35355.0  1976  8.780787
33776    35355.0  1977  9.086702
33777    35356.0  1975  8.348064
33778    35356.0  1976  7.288244

[33779 rows x 3 columns]

In [4]:
variables_list = data.columns.tolist()

In [5]:
print(variables_list)

['person_ID', 'year', 'log_wage']


In [6]:
variance_by_year = data.groupby('year')['log_wage'].var()

In [45]:
covariance_across_years = data.pivot_table(index='person_ID', columns='year', values='log_wage').cov()
display(covariance_across_years)
data_moments = covariance_across_years.reset_index()
data_moments = data_moments.iloc[:,1:].values
data_moments = data_moments.reshape(-1,1)
display(data_moments)

year      1974      1975      1976      1977      1978      1979      1980  \
year                                                                         
1974  0.380232  0.266168  0.223703  0.232121  0.247309  0.219021  0.192690   
1975  0.266168  0.411052  0.269560  0.253488  0.267063  0.234334  0.205848   
1976  0.223703  0.269560  0.466307  0.298764  0.262443  0.218654  0.206554   
1977  0.232121  0.253488  0.298764  0.546291  0.306649  0.255678  0.238145   
1978  0.247309  0.267063  0.262443  0.306649  0.579645  0.314938  0.268837   
1979  0.219021  0.234334  0.218654  0.255678  0.314938  0.502633  0.304382   
1980  0.192690  0.205848  0.206554  0.238145  0.268837  0.304382  0.509569   
1981  0.172943  0.190847  0.179327  0.254721  0.264958  0.266425  0.342281   
1982  0.174611  0.198061  0.199280  0.228993  0.234453  0.261171  0.302340   
1983  0.186813  0.187549  0.209063  0.215633  0.233428  0.252946  0.297831   
1984  0.171124  0.181489  0.195643  0.236753  0.244582  0.260685  0.303705   
1985  0.169817  0.159429  0.185495  0.205950  0.213733  0.229166  0.259129   
1986  0.186373  0.175009  0.181148  0.230313  0.201749  0.218492  0.251555   
1987  0.150952  0.169591  0.182515  0.207437  0.210650  0.196992  0.224739   
1988  0.141803  0.154137  0.157680  0.188814  0.173736  0.186591  0.221790   
1989  0.177476  0.191548  0.162372  0.206426  0.174617  0.201091  0.222968   
1990  0.144341  0.177200  0.176461  0.198869  0.163338  0.176052  0.194946   
1991  0.129477  0.153252  0.183787  0.219495  0.143215  0.165536  0.182388   
1992  0.109535  0.147261  0.153181  0.166731  0.140366  0.164548  0.200839   

year      1981      1982      1983      1984      1985      1986      1987  \
year                                                                         
1974  0.172943  0.174611  0.186813  0.171124  0.169817  0.186373  0.150952   
1975  0.190847  0.198061  0.187549  0.181489  0.159429  0.175009  0.169591   
1976  0.179327  0.199280  0.209063  0.195643  0.185495  0.181148  0.182515   
1977  0.254721  0.228993  0.215633  0.236753  0.205950  0.230313  0.207437   
1978  0.264958  0.234453  0.233428  0.244582  0.213733  0.201749  0.210650   
1979  0.266425  0.261171  0.252946  0.260685  0.229166  0.218492  0.196992   
1980  0.342281  0.302340  0.297831  0.303705  0.259129  0.251555  0.224739   
1981  0.542037  0.350024  0.310555  0.303280  0.266673  0.255760  0.252414   
1982  0.350024  0.629157  0.348557  0.348459  0.345709  0.325680  0.278233   
1983  0.310555  0.348557  0.701649  0.423167  0.401102  0.390195  0.360385   
1984  0.303280  0.348459  0.423167  0.746107  0.443361  0.407637  0.350220   
1985  0.266673  0.345709  0.401102  0.443361  0.689860  0.446360  0.379651   
1986  0.255760  0.325680  0.390195  0.407637  0.446360  0.681613  0.420080   
1987  0.252414  0.278233  0.360385  0.350220  0.379651  0.420080  0.684493   
1988  0.247930  0.278888  0.326801  0.338189  0.340567  0.384888  0.391887   
1989  0.234822  0.255396  0.294632  0.320238  0.351953  0.354968  0.381379   
1990  0.210068  0.245366  0.311031  0.286285  0.312728  0.349163  0.341647   
1991  0.193489  0.252007  0.275667  0.280938  0.313358  0.313051  0.318024   
1992  0.201162  0.219352  0.267655  0.270830  0.281033  0.286647  0.277021   

year      1988      1989      1990      1991      1992  
year                                                    
1974  0.141803  0.177476  0.144341  0.129477  0.109535  
1975  0.154137  0.191548  0.177200  0.153252  0.147261  
1976  0.157680  0.162372  0.176461  0.183787  0.153181  
1977  0.188814  0.206426  0.198869  0.219495  0.166731  
1978  0.173736  0.174617  0.163338  0.143215  0.140366  
1979  0.186591  0.201091  0.176052  0.165536  0.164548  
1980  0.221790  0.222968  0.194946  0.182388  0.200839  
1981  0.247930  0.234822  0.210068  0.193489  0.201162  
1982  0.278888  0.255396  0.245366  0.252007  0.219352  
1983  0.326801  0.294632  0.311031  0.275667  0.267655  
1984  0.338189  0.320238  0.286285  0.

array([[0.38023182],
       [0.26616782],
       [0.22370324],
       [0.23212118],
       [0.24730907],
       [0.21902123],
       [0.19269017],
       [0.17294339],
       [0.17461068],
       [0.18681347],
       [0.17112422],
       [0.16981702],
       [0.1863726 ],
       [0.15095206],
       [0.14180332],
       [0.17747562],
       [0.14434097],
       [0.12947747],
       [0.10953476],
       [0.26616782],
       [0.4110522 ],
       [0.26955968],
       [0.25348755],
       [0.26706259],
       [0.23433364],
       [0.20584785],
       [0.19084692],
       [0.19806132],
       [0.18754893],
       [0.18148936],
       [0.15942907],
       [0.17500921],
       [0.16959091],
       [0.15413713],
       [0.19154803],
       [0.17719999],
       [0.15325182],
       [0.14726136],
       [0.22370324],
       [0.26955968],
       [0.46630692],
       [0.29876361],
       [0.26244273],
       [0.218654  ],
       [0.20655434],
       [0.17932698],
       [0.19927958],
       [0.209

In [38]:
def simulate_income_data(var_alpha, rho, var_eta, var_epsilon, num_individuals, num_periods):

    np.random.seed(4) # VVD
    
    # Simulate individual-specific fixed effects
    individual_fixed_effects = np.random.normal(scale=np.sqrt(var_alpha), size=num_individuals)
    
    # Initialize DataFrame to store simulated income data
    simulated_data = pd.DataFrame(index=range(num_individuals), columns=range(num_periods))
    
    # Simulate income data for each individual
    for i in range(num_individuals):

        # Initialise the autoregressive process
        z_process = 0
        
        # Generate income data for each period
        for t in range(num_periods):
            
            # Simulate shock to the autoregressive process
            eta = np.random.normal(scale=np.sqrt(var_eta))
            
            # Update autoregressive process
            z_process = rho * z_process + eta
            
            # Simulate income for the current period
            income = individual_fixed_effects[i] + z_process + np.random.normal(scale=np.sqrt(var_epsilon))
            
            # Store simulated income in DataFrame
            simulated_data.at[i, t] = income
    
    cov_matrix = simulated_data.cov()

    simulated_moments = cov_matrix.values

    simulated_moments = simulated_moments.reshape(-1,1) 

    return simulated_moments

In [50]:
# Simulate income data
simulated_moments = simulate_income_data(var_alpha=0.1, rho=0.73, var_eta=0.1, var_epsilon=0.1, num_individuals=1000, num_periods=19)
print(simulated_moments)

[[0.2984484 ]
 [0.16909194]
 [0.15440805]
 [0.14729676]
 [0.13944149]
 [0.12049236]
 [0.09775345]
 [0.10958404]
 [0.1060014 ]
 [0.1179434 ]
 [0.10124604]
 [0.08771566]
 [0.09922365]
 [0.07838636]
 [0.0880495 ]
 [0.08037241]
 [0.08893554]
 [0.1014873 ]
 [0.09682906]
 [0.16909194]
 [0.35424501]
 [0.21991708]
 [0.17703086]
 [0.16404611]
 [0.13646016]
 [0.12355075]
 [0.12658857]
 [0.11368389]
 [0.11673032]
 [0.11151917]
 [0.10904279]
 [0.10360788]
 [0.08290017]
 [0.0813417 ]
 [0.07817116]
 [0.09722642]
 [0.11336916]
 [0.09007588]
 [0.15440805]
 [0.21991708]
 [0.38691573]
 [0.24378793]
 [0.20317714]
 [0.16345006]
 [0.137905  ]
 [0.13295453]
 [0.11673223]
 [0.11562566]
 [0.12699602]
 [0.10545624]
 [0.11195787]
 [0.08974862]
 [0.09959976]
 [0.08623106]
 [0.08687751]
 [0.09481699]
 [0.08742009]
 [0.14729676]
 [0.17703086]
 [0.24378793]
 [0.40612353]
 [0.24458831]
 [0.1892098 ]
 [0.16263428]
 [0.1297742 ]
 [0.11471238]
 [0.11755842]
 [0.13059019]
 [0.11080466]
 [0.10608719]
 [0.08308799]
 [0.09

In [51]:
def distance(simulated_moments, data_moments):

    distance = np.transpose(simulated_moments) * data_moments

    return distance

In [52]:
distance = distance(simulated_moments, data_moments)
print(distance)

[[0.11347958 0.06429414 0.05871085 ... 0.0641403  0.0848546  0.14047509]
 [0.07943736 0.04500683 0.04109845 ... 0.04489915 0.05939946 0.09833461]
 [0.06676387 0.03782641 0.03454158 ... 0.03773591 0.04992283 0.08264625]
 ...
 [0.1065643  0.06037615 0.0551331  ... 0.06023169 0.07968369 0.13191475]
 [0.12514262 0.07090207 0.06474495 ... 0.07073243 0.09357566 0.15491264]
 [0.21012081 0.11904817 0.10871006 ... 0.11876333 0.15711829 0.26010619]]


In [ ]:
def SMM(var_alpha, rho, var_eta, var_epsilon, num_individuals, num_periods, toler = 1e-6):
    
    w = np.eye(num_periods)

    error = toler + 1

    while error > toler:

        simulated_data = simulate_income_data(var_alpha, rho, var_eta, var_epsilon, num_individuals, num_periods)

        cov_matrix = simulated_data.cov()

        loss = cov_matrix.T * w * cov_matrix

        

    
    


